apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-emissary-deployment
  labels:
    container: app-emissary
spec:
  replicas: 10
  selector:
    matchLabels:
      container: app-emissary
  template:
    metadata:
      labels:
        container: app-emissary
    spec:
      containers:
        - name: app-emissary
          image: owasp/zap2docker-stable:s2021-12-16
          command:
            [
              "zap.sh",
              "-daemon",
              "-port",
              "8080",
              "-host",
              "0.0.0.0",
              "-config",
              "api.addrs.addr.regex=true",
              "-config",
              "api.addrs.addr.name=zap|localhost|127.0.0.1|172.25.0.*|appemissary_zap_(100|[1-9][0-9]?)",
              "-config",
              "api.key=${ZAP_API_KEY}",
            ]

---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  labels:
    container: app-emissary
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: "8082"
      port: 8082
      targetPort: 8080
    - name: "8083"
      port: 8083
      targetPort: 8080
    - name: "8084"
      port: 8084
      targetPort: 8080
    - name: "8085"
      port: 8085
      targetPort: 8080
    - name: "8086"
      port: 8086
      targetPort: 8080
    - name: "8087"
      port: 8087
      targetPort: 8080
    - name: "8088"
      port: 8088
      targetPort: 8080
    - name: "8089"
      port: 8089
      targetPort: 8080
    - name: "8090"
      port: 8090
      targetPort: 8080
    - name: "8091"
      port: 8091
      targetPort: 8080
  selector:
    container: app-emissary
